/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyComponentB {
      'first': string;
      'last': string;
    }
  }

  interface HTMLMyComponentBElement extends StencilComponents.MyComponentB, HTMLStencilElement {}

  var HTMLMyComponentBElement: {
    prototype: HTMLMyComponentBElement;
    new (): HTMLMyComponentBElement;
  };
  interface HTMLElementTagNameMap {
    'my-component-b': HTMLMyComponentBElement;
  }
  interface ElementTagNameMap {
    'my-component-b': HTMLMyComponentBElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component-b': JSXElements.MyComponentBAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentBAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
